# Array Indexing and Slicing in NumPy
## Introducing Array Indexing and Slicing
Welcome back! Today, we are exploring Array Indexing and Slicing, two crucial concepts for data manipulation and processing. Utilizing Python's NumPy library, by the end of this lesson, you will be able to comfortably access and modify elements in a NumPy array.



In [1]:
!pip install nptyping

Certainly! Let's dive into **nptyping**, a powerful addition to enhance type safety in your NumPy workflows, especially for applications like Agentic AI, where precision and clarity in data structures are crucial.

---

## **What is `nptyping`?**

**`nptyping`** is a Python library designed to add static typing capabilities to NumPy arrays. It integrates seamlessly with Python's `typing` module, providing explicit types for arrays, shapes, and dtypes, which is especially useful for large, complex AI projects like Agentic AI.

By using `nptyping`, you can specify:
1. **Array types** (`nptyping.NDArray`): Define the data type and shape of arrays.
2. **Shapes**: Enforce constraints on the array dimensions.
3. **Dtypes**: Ensure the array elements conform to specific data types.

---

## **Why Use `nptyping` in NumPy?**

### 1. **Enhanced Code Clarity**
   - When working with AI, it’s common to deal with high-dimensional tensors or specific data shapes. By specifying the types explicitly, your code becomes self-documenting.

   ```python
   from nptyping import NDArray, Int, Shape

   # Example: 3x3 matrix of integers
   Matrix = NDArray[Shape["3, 3"], Int]
   ```

### 2. **Static Type Checking**
   - Tools like `mypy` can analyze your code and catch bugs early. For instance, if a function expects a specific array shape but receives an incompatible one, you'll be alerted during development.

   ```python
   def process_matrix(matrix: Matrix) -> int:
       return matrix.sum()
   ```

### 3. **Fewer Runtime Errors**
   - Incorrect dimensions or data types are common pitfalls in AI workflows. `nptyping` validates these issues at a static level.

### 4. **Simplified Debugging**
   - Errors in AI models often stem from mismatched dimensions or data types. Using `nptyping` ensures these issues are addressed before execution.

---

## **Benefits for Agentic AI**

1. **Structured Data Flow**: In Agentic AI, agents often interact with diverse datasets. `nptyping` ensures agents process data correctly, maintaining reliability.

2. **Interoperability**: When integrating NumPy with frameworks like TensorFlow or PyTorch, `nptyping` helps maintain consistency in shapes and data types.

3. **Scalability**: For large AI projects, consistent type annotations make codebases easier to manage, scale, and maintain.

4. **Safety in Parallel Computing**: When splitting computations across multiple agents or threads, ensuring type safety minimizes synchronization errors.

---

## **Practical Example**

Here’s an example demonstrating the benefits of `nptyping` in an AI agent scenario:

```python
from nptyping import NDArray, Float, Shape
import numpy as np

# Define a 2D array of floats
Image = NDArray[Shape["256, 256"], Float]

def preprocess_image(image: Image) -> Image:
    """
    Normalize image data to range [0, 1].
    """
    return image / 255.0

# Correct shape and dtype
input_image: Image = np.random.rand(256, 256).astype(np.float64)

# Preprocessing
normalized_image = preprocess_image(input_image)
print(normalized_image)
```

### Key Features:
- **Type Enforced**: Passing an incorrectly shaped array (e.g., 128x128) would raise a static error.
- **Clear Intent**: The function signature tells you what the function expects and returns.

---

## **How to Install and Use `nptyping`**

1. **Installation**:
   ```bash
   pip install nptyping
   ```

2. **Common Import Patterns**:
   ```python
   from nptyping import NDArray, Shape, Int, Float
   ```

3. **Integration with `mypy`**:
   - Use `mypy` to check your code statically:
     ```bash
     mypy your_script.py
     ```

---

## **Limitations**

1. **Runtime Validation**: `nptyping` annotations are for static checks. For runtime validations, additional checks are needed.
2. **Complexity**: Overuse can lead to verbose code in simple scripts.

---

## **Conclusion**

By incorporating `nptyping`:
- You bring **type safety** and **clarity** to your NumPy workflows.
- It’s a **game-changer** for Agentic AI, ensuring your agents handle structured data predictably.
- The ability to **define array shapes and types statically** improves development speed and reduces debugging time.

In Agentic AI, where precision and scalability matter, `nptyping` is a vital tool for building robust, error-free systems. 🚀

# Quick Refresher on NumPy Arrays
Let's quickly revisit NumPy arrays. A NumPy array is a powerful tool for numerical operations. Here's how we import NumPy and create a simple array:

In [5]:
import numpy as np
from nptyping import NDArray, Shape
from typing import Any

arr : NDArray[Shape['4'] , Any] = np.array([1, 2, 3, 4])
display(arr)


array([1, 2, 3, 4])

In [6]:
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
# Opposite indexing
print(arr[-1])


1
2
3
4
4


In [10]:
print(arr[0])
print("+")
print(arr[3])
print("=")
print(arr[0] + arr[3])

1
+
4
=
5


# Unwrapping Array Slicing
Array slicing lets us access a subset, or slice, of an array. The basic syntax for slicing in Python is array[start:stop:step].

Let's check this out:

In [ ]:
print(arr[1:3]) # [2 , 3]
print(arr[2:3]) # [3]
print(arr[::2]) # [1 , 3]


[2 3]
[3]
[1 3]


As a reminder, stop is not included, so [1:3] gives us elements with indices 2, 3. Also remember that we can skip any of arguments to make them default. Thus, [::2] specifies only the step parameter, so start and end are filled with the default value.

Let's recall the default values:

- start = 0
- end = len(array)
- step = 1

One important thing to know: if we modify elements in a sliced array, it also modifies the original array:

In [11]:
new_arr = arr[1:3]
new_arr[1] = 10
print(arr)

[ 1  2 10  4]


# Indexing and Slicing in Multi-dimensional Arrays
Now, let's move to multi-dimensional arrays and try out these operations. We'll use a 2D array for illustration:

In [12]:
import numpy as np
from nptyping import NDArray, Shape
from typing import Any

arr_multi : NDArray[Shape['3 , 4'] , Any] = np.array([[1 , 2 , 3 , 4],
                                                      [5, 6 , 7 , 8],
                                                      [1 , 2 , 3 , 4]]
                                                    )
print(arr_multi)


[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]]


In [14]:
print(arr_multi[0, 2])  # 3
print(arr_multi[1])  # array([5, 6 , 7, 8])
print(arr_multi[:, 2])  # array([3, 7, 3])

3
[5 6 7 8]
[3 7 3]


Slicing on multi-dimensional arrays is also simple. We can retrieve the first two rows and first two columns, for instance:

In [15]:
print(arr_multi[:2, :2])
print(arr_multi[1:, 2:])

[[1 2]
 [5 6]]
[[7 8]
 [3 4]]
